//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garment_Factory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Equipment_ID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastReview { get; set; }
        public int Warehouse_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
