//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garment_Factory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Textile
    {
        public string Name { get; set; }
        public int AvailableSquare { get; set; }
        public double PricePerSquare { get; set; }
        public double Thickness { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public int Textile_ID { get; set; }
        public Nullable<int> Warehouse_ID { get; set; }
        public int Supplier_ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
